### ISSUE TITLE
Failed count not displaying on Command prompt even the execution is failed. But the failed file is present in Failed folder

### ISSUE THREAD

**Issue by KAjayKumar** [AbhishikthaReddy/Tests_Automation#28]
![failed count not displaying1](https://user-images.githubusercontent.com/32909971/31833451-385c5034-b5e8-11e7-9859-e1b9c44dc88e.jpg)
Failed count not displaying on Command prompt even the execution is failed. But the failed file is present in Failed folder

Added the files to run in master json file
 After execution verified the Result, Pass and fail folder.
 Verify the Summary Result

**Comment by AbhishikthaReddy** [comment]
command prompt doesn't display any result related to the scenarios. That' not the requirement
